version: '3.8'

services:
  app:
    image: chronomind
    build: .
    command: npm run start:dev 
    volumes:
      - .:/app 
      - /app/node_modules
    environment:
      NODE_ENV: development
