version: '3.8'

services:
  app:
    image: chronomind
    build: .
    command: npm run start:prod # ⚡ 生产模式，不支持热更新
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: manager
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: chronomind
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
